# Generated by Django 3.0.5 on 2020-04-26 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burgers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='burger',
            name='ingredientes',
            field=models.ManyToManyField(blank=True, null=True, to='burgers.Ingredient'),
        ),
    ]
