# Generated by Django 3.0.5 on 2020-04-30 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burgers', '0003_auto_20200427_0031'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='path',
            field=models.URLField(null=True),
        ),
    ]
