# Generated by Django 3.0.5 on 2020-04-30 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burgers', '0004_ingredient_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='burger',
            name='imagen',
            field=models.URLField(),
        ),
    ]
